### ISSUE TITLE
Method getOutlineStep panics because of a seg fault

### ISSUE THREAD

**Issue by phramos07** [go-bdd/gobdd#141] opened 2022-06-28 18:53 UTC
Current version: v.1.1.3

In line 353 of gobdd.go file we have (inside the method `getOutlineStep` :

```
if len(stepsList) == 0 {
    return newSteps
}
```

However in line 360 we have

```
newSteps = append(newSteps, stepsList[si][ci])
```

So, whenever `stepsList` comes with a "nil" inside first position, like `stepsList = [nil]`, this will result in a seg fault. I'm just facing it while trying to parse this `feature` file step:

```
Given The setup with <param1> and <param2> :
    Examples:
      | param1  | param2 |
      | False       |    True   |
```

With this gobdd code:

```
func getSetup_outlinetest(t gobdd.StepTest, ctx gobdd.Context) {}

func TestScenarios(t *testing.T) {
	suite := gobdd.NewSuite(t, gobdd.WithFeaturesPath(PATH))
	suite.AddStep(`The setup with <param1> and <param2> :`, getSetup_outlinetest)
	suite.Run()
```

Running this test is resulting in a seg fault / panic.

**Comment by bkielbasa** [comment] 2022-07-07 05:34
thanks for the bug report! I'll investigate the issue and prepare a fix soon.

**Comment by bkielbasa** [comment] 2022-07-25 07:10
Hi, I created a test in the draft PR https://github.com/go-bdd/gobdd/pull/142 for this issue but I cannot reproduce it. Could you help me with it a bit?

**Comment by phramos07** [comment] 2022-08-24 18:32
@bkielbasa I'm sorry for the late reply. I'll post a step-by-step to reproduce it as soon as possible.

**Comment by bkielbasa** [comment] 2022-12-05 08:51
I cannot reproduce it. Pls reopen the ticket when you have the problem again and give me steps to reproduce it. Closing for now.

**Closed by bkielbasa** 2022-12-05 08:51 UTC
Labels: bug
